### ISSUE TITLE
sitemap not being included in robots.txt

### ISSUE THREAD

**Issue by myusuf3** [jazzband/django-robots#13] opened 2013-07-11 05:06 UTC
I have tried both default discovery as well as specifying it manually using the `ROBOTS_SITEMAP_URLS` setting but I am still unable to get the site map to show up on the `robots.txt`

**Comment by yakky** [comment] 2015-12-22 07:43
@myusuf3 @tezro I cannot reproduce this, could you provide more details?

**Comment by myusuf3** [comment] 2015-12-23 01:39
woo! wayback machine here. I dont even remember creating this issue.

**Comment by SalahAdDin** [comment] 2015-12-24 05:21
:+1:

**Comment by mheppner** [comment] 2016-09-06 04:09
I know this is a pretty old issue, but I wanted to clarify that `reverse()` does not pick up on the sitemap if it's behind `cache_page()` in your URL conf. It might be helpful for others to update the documentation. In my case, I was using a main index (`django.contrib.sitemaps.views.index`) which linked off to the sections (`django.contrib.sitemaps.sitemap`), so I just took off the caching for the index and `django-robots` could then reverse to it. The sections can still be cached.

Alternatively, if you just had 1 sitemap, it seems to work fine if you create an alias view and don't use `cache_page()` directly in your URL conf:

```python
# views.py
from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page

@cache_page(10 * 60)
def sitemap_index(*args, **kwargs):
    return sitemaps_views.index(*args, **kwargs)
```

**Comment by yakky** [comment] 2017-02-04 17:13
@mheppner when merged, could you check if the fix for #61 solves the cache issue?

**Comment by myusuf3** [comment] 2017-02-06 19:14
4 years guys.

**Comment by jezdez** [comment] 2017-02-06 21:01
@myusuf3 For the record, that type of snark is counter-productive and I think you should know better. Please be so kind and stop giving this type of feedback.

**Comment by mheppner** [comment] 2017-02-06 22:30
I sure can @yakky. ETA on the merge? The one you linked is just the issue, did you mean #71?

**Comment by yakky** [comment] 2017-02-07 09:13
@mheppner actually this commit https://github.com/jazzband/django-robots/pull/71/commits/ba2d5b60d7f5674fd3d75b85f37e11c7778d2699 sorry
When I wrote the above comment I thought I would have opened a Pr specific for the deprecation but it ended up with the whole general Django version update
I would like to wrap everything by the end of the week

**Comment by mheppner** [comment] 2017-02-07 14:35
@yakky the link to that commit doesn't work either lol. I'll check out your branch this evening.

**Comment by yakky** [comment] 2017-02-07 15:09
@mheppner :man_facepalming:

**Comment by mheppner** [comment] 2017-02-08 05:56
@yakky I tried the features/djangos branch and that didn't seem to change anything. Everything else was fine though. I think the problem me and @andreyshipilov were having is just how [`cache_page()` behaves](http://stackoverflow.com/a/11027531/492920). That answer is from 2012, so maybe something has changed, but I can't find anything. 

What about adding a setting to django-robots for specifying a named URL to reverse to?

**Comment by yakky** [comment] 2017-02-11 09:05
@mheppner I'm not super fond of adding settings, but it seems adequate to cover this case

**Comment by yakky** [comment] 2017-02-11 09:58
@mheppner @andreyshipilov could you please check the linked pr?

**Comment by mheppner** [comment] 2017-02-13 15:10
@yakky looks good to me, thanks! 😃

**Comment by yakky** [comment] 2017-02-13 18:17
@mheppner thanks for the review!

**Closed** 2017-02-13 18:17 UTC

**Comment by andreyshipilov** [comment] 2017-02-14 02:05
@yakky Works for me too :)

**Comment by yakky** [comment] 2017-02-15 23:35
@andreyshipilov :+1:  thanks

**Comment by SalahAdDin** [comment] 2017-02-24 12:08
@yakky For when have you planned release a new version?

**Comment by yakky** [comment] 2017-02-24 17:28
@SalahAdDin with a little luck this weekend

**Comment by SalahAdDin** [comment] 2017-02-25 17:49
@yakky, oh i hope!

**Comment by yakky** [comment] 2017-02-26 18:41
@SalahAdDin 3.0rc1 has been released on Pypi. I'm going to check if everything is ok and I will release 3.0 final in a couple of days (sooner if you could confirm rc1 is fine! ;) )

**Comment by SalahAdDin** [comment] 2017-02-27 12:57
Man, i have a problem using the new url version:
![seleccion_297](https://cloud.githubusercontent.com/assets/5034215/23362092/c8753ec4-fcfc-11e6-9430-d661ea6c430b.png)
This argument is the problem: `{'sitemaps': []}`.
I think is a problem because i'm using `wagtail`'s sitemap view. So, deleting this argument cached view works very well.

**Comment by mheppner** [comment] 2017-02-27 15:55
@SalahAdDin Can you give more information about this? Where is that argument you're talking about? For what it's worth, Wagtail doesn't use Django's sitemap framework, they're [rolling their own](https://github.com/wagtail/wagtail/tree/master/wagtail/contrib/wagtailsitemaps), which means django-robots won't be reversing to it automatically. Can you try giving your URL a name and setting it to `ROBOTS_SITEMAP_VIEW_NAME`?

**Comment by SalahAdDin** [comment] 2017-02-27 19:09
@mheppner Yes, i did it, i only delete these argument, and works fine.

**Comment by yakky** [comment] 2017-02-28 03:25
@SalahAdDin @mheppner thanks for helping with this. Would you check if linked PR clarifies how to correctly configure robots in the case above?

**Comment by mheppner** [comment] 2017-02-28 04:36
Ah, now I see what @SalahAdDin was talking about. @yakky, yeah I think that clears it up 👍

**Comment by mheppner** [comment] 2017-02-28 05:01
@yakky I just tried 3.0rc1 and everything seems to be working, thanks! 🥇
