### ISSUE TITLE
Migration not working

### ISSUE THREAD

**Issue by justin-ven** [jazzband/django-robots#125] opened 2022-01-31 14:37 UTC
Related to #124, a migration file now seems to be included in 5.0, but results (at least on my system) in the following error: 

psycopg2.errors.ObjectNotInPrerequisiteState: sequence must have same owner as table it is linked to

**Comment by svandeneertwegh** [comment] 2022-03-28 09:46
Agree, i have the same issue

**Comment by svandeneertwegh** [comment] 2022-03-28 09:54
When i copie the project direct in my project and remove 0002 migration. Then run `manage.py makemigrations robots`, it returns "No changes detected in app 'robots'".

**Comment by tony** [comment] 2022-04-23 10:50
This needs more information. 

Not clear if this is a configuration issue on your side or if it's a django-robots issue. 

> psycopg2.errors.ObjectNotInPrerequisiteState: sequence must have same owner as table it is linked to

@svandeneertwegh @justin-ven It looks like you may need superuser access / to iron permissions out.  Have you tried troubleshooting yet on the postgres side?

**Comment by justin-ven** [comment] 2022-05-09 13:38
This issue is now resolved on my system - I just upgraded to Django 4.0.3, and let the migration set up and work through.  I did need to merge two migrations on one system, but otherwise things seem to be functioning correctly for me now.

**Comment by tony** [comment] 2022-10-15 15:06
> Related to https://github.com/jazzband/django-robots/issues/124

I am about to release a beta release of 5.x that includes a missing app setting via #134 - in re #124.

**Comment by tony** [comment] 2022-10-15 15:19
In re:

> ... results (at least on my system) in the following error:
> 
> psycopg2.errors.ObjectNotInPrerequisiteState: sequence must have same owner as table it is linked to
> 
> ```
> psycopg2.errors.ObjectNotInPrerequisiteState: sequence must have same owner as table it is linked to
> ```

I'm don't think this is something the package itself can solve - I'm open to being convinced otherwise. 

These are highly specific to your own project's state, migrations are complicated.

<details>

**Don't take my word on these! It depends 100% on your specific system**

- You may need to go in manually to `django_migrations` and see if a migration really ought to be run
- It may be a case where `makemigrations` was ran to headoff the problem is #124, in which case you **could** need to remove the offending row and `./manage.py migrate robots --fake`. 
- Check which version of django-robots you're using
  - 5.0 has a migration for `BigAutoField` but is missing a local app-related setting (fixed via #134, build yet to be released, likely as 5.1beta0, 5.1beta, etc

</details>

I will close, but keep the issue unlocked so **workarounds / solutions can be shared**. I'm not sure if it's #124 or not.

There's a stackoverflow questions here: https://stackoverflow.com/q/70761679/1396928

**Closed by tony** 2022-10-15 15:19 UTC
